### PR TITLE
Decompile s08b_bunsin2_800C8F04.s

### PR DESCRIPTION
**Pull request by DarrenSweeney**
Picked a very simple function, small commit to get back into decompiling and testing local setup.

### CODE REVIEW

**Comment by KieronJ** [comment]
This file should be under animal/ninja/bunsin2.c

**Comment by DarrenSweeney** [comment]
Gotcha, I'll fix that, how did you know it's that path? How do I find that out myself?

**Comment by DarrenSweeney** [comment]
Where can I find that info for myself? Out of curiosity.

**Comment by DarrenSweeney** [comment]
whoops

**Pull request merged**
